version: "3"

services:
  my-app:
    build: ./app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000/users || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
